image: node:16.19.1

# prebuild the workspace to speed up development
tasks:
  - init: |
      sudo apt-get update && sudo apt-get install -y postgresql postgresql-contrib

    # Start Postgres and create a new database and user
      sudo service postgresql start
      sudo -u postgres createdb codechallenge
      sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD 'admin';"
      sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE codechallenge TO postgres;"

    # Install dependencies for frontend and backend
      cd backend
      npm install
      cd ../frontend
      npm install
      ng build

  - command: |
      cd backend
      node index.js
    # Start the frontend server
      cd ../frontend
      ng serve --host 0.0.0.0 --disable-host-check 
      
# start the backend server and the frontend app
# then open the app in a new browser tab
ports:
  - port: 4500
    onOpen: ignore
  - port: 4200
    onOpen: open-browser

# specify the default workspace layout
layout: 
  - "frontend 50% 50%"
  - "backend 50% 50%"
