image: node:16.19.1
# prebuild the workspace to speed up development

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codechallenge
      MYSQL_USER: treatapp
      MYSQL_PASSWORD: TBbccc547

tasks:
  - name: Terminal 
    init: cd frontend && npm install && npm install && npm install -g @angular/cli@13.1.0
    command: npm run start-local 
      

ports:
  - port: 4500
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
