image: node:16.19.1
# prebuild the workspace to speed up development
tasks:
  - name: Terminal 
    init: cd frontend  && npm install 
    command: ng serve --host 0.0.0.0 --disable-host-check 
      

ports:
  - port: 4500
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
