image: node:16.19.1
# prebuild the workspace to speed up development
tasks:
  - name: Terminal 
    init: npm install 
    command: npm install npm@latest 
             cd ../frontend  
             npm install @angular/cli@13.1.0 
             npm install
             ng serve --host 0.0.0.0 --disable-host-check 
      

ports:
  - port: 4500
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
