image:
  file: .gitpod.Dockerfile
  
# prebuild the workspace to speed up development

tasks:
  - name: Run Backend App 
    init: cd backend && npm install
    command: |
            sudo service postgresql start
            sudo psql -U postgres -c "CREATE DATABASE codechallenge;" 
            sudo psql -U postgres -c "CREATE USER treatuser WITH PASSWORD 'admin';" 
            sudo psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE codechallenge TO treatuser;"
            node index.js
  - name: Run Frontend App 
    init: cd frontend && npm install && npm install -g @angular/cli@13.1.0
    command: npm run start-local 

ports:
  - port: 4500
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
