image:
  file: .gitpod.Dockerfile
  
# prebuild the workspace to speed up development

tasks:
  - before: sudo service postgresql start
            psql -U postgres -c "CREATE DATABASE codechallenge;" 
            psql -U postgres -c "CREATE USER treatuser WITH PASSWORD 'admin';" 
            psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE codechallenge TO treatuser;" 
  - name: Run Backend App 
    init: cd backend && npm install
    command: node index.js
  - name: Run Frontend App 
    init: cd frontend && npm install && npm install -g @angular/cli@13.1.0
    command: npm run start-local 

ports:
  - port: 4500
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
