image: gitpod/workspace-full

# prebuild the workspace to speed up development
tasks:
  - name: Prebuild Workspace
    command: |
      sudo apt-get update && sudo apt-get install -y postgresql
      sudo service postgresql start
      sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD 'admin';"
      sudo -u postgres createdb codechallenge
      cd backend
      npm install
      cd ../frontend
      npm install
      ng build

# start the backend server and the frontend app
# then open the app in a new browser tab
ports:
  - port: 4500
    onOpen: node backend/app.js
  - port: 4200
    onOpen: ng serve --host 0.0.0.0

# expose the postgres database port
# so that it can be accessed by the backend
# and other tools such as DBeaver or pgAdmin
ports:
  - port: 5432
    onOpen: sudo service postgresql start

# open the app in a new browser tab
tasks:
  - name: Open Browser
    command: gp await-port 4200 && gp preview $(gp url 4200)

# specify the default workspace layout
layout: 
  - "frontend 50% 50%"
  - "backend 50% 50%"
